name: Docker Image CI

on:
  pull_request:
    branches:
      - master

jobs:

  pr_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build .
